import { useEffect, useState } from "react";
import { auth } from "./firebase";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { collection, getDocs } from "firebase/firestore";
import { db } from "./firebase";
import { BrowserRouter as Router, Routes, Route, Navigate } from "react-router-dom";

import Edit_Profile from "./Edit_Profile"; 
import Preferences from "./Preferences";
import Subscription from "./Subscription";
import Login from "./Login";
import SplashScreen from "./SplashScreen";
import Welcome from "./Welcome"; 

function App() {
  const [user, setUser] = useState(null);
    const [stories, setStories] = useState([]);
      const [loadingSplash, setLoadingSplash] = useState(true);
        const [authLoading, setAuthLoading] = useState(true); // 👈 for spinner

          // Show splash for 3s
            useEffect(() => {
                const timer = setTimeout(() => setLoadingSplash(false), 3000);
                    return () => clearTimeout(timer);
                      }, []);

                        // Track auth state
                          useEffect(() => {
                              const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
                                    setUser(currentUser);
                                          setAuthLoading(false); // 👈 stop spinner once Firebase responds
                                              });
                                                  return () => unsubscribe();
                                                    }, []);

                                                      // Fetch stories only if user is logged in
                                                        useEffect(() => {
                                                            if (!user) return;
                                                                async function fetchStories() {
                                                                      const querySnapshot = await getDocs(collection(db, "stories"));
                                                                            setStories(querySnapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })));
                                                                                }
                                                                                    fetchStories();
                                                                                      }, [user]);

                                                                                        // ✅ Splash first
                                                                                          if (loadingSplash) {
                                                                                              return <SplashScreen />;
                                                                                                }

                                                                                                  // ✅ Show spinner while Firebase checks login
                                                                                                    if (authLoading) {
                                                                                                        return (
                                                                                                              <div className="flex items-center justify-center min-h-screen bg-black">
                                                                                                                      <div className="w-12 h-12 border-4 border-gray-300 border-t-blue-500 rounded-full animate-spin"></div>
                                                                                                                            </div>
                                                                                                                                );
                                                                                                                                  }

                                                                                                                                    return (
                                                                                                                                        <Router>
                                                                                                                                              <div>
                                                                                                                                                      {/* ✅ Floating Logout Button (only if logged in) */}
                                                                                                                                                              {user && (
                                                                                                                                                                        <button
                                                                                                                                                                                    onClick={() => signOut(auth)}
                                                                                                                                                                                                style={{
                                                                                                                                                                                                              position: "fixed",
                                                                                                                                                                                                                            top: 10,
                                                                                                                                                                                                                                          right: 10,
                                                                                                                                                                                                                                                        zIndex: 1000,
                                                                                                                                                                                                                                                                      background: "red",
                                                                                                                                                                                                                                                                                    color: "white",
                                                                                                                                                                                                                                                                                                  padding: "6px 12px",
                                                                                                                                                                                                                                                                                                                borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                              border: "none",
                                                                                                                                                                                                                                                                                                                                            cursor: "pointer"
                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                              🚪 Log Out
                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                        <Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                  {/* If no user → always go to login */}
                                                                                                                                                                                                                                                                                                                                                                                                                            {!user ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                        <Route path="*" element={<Login onLogin={setUser} />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* After login → Welcome screen first */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Route path="/" element={<Welcome user={user} />} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Route path="/subscription" element={<Subscription />} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Route path="/Preferences" element={<Preferences />} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Route path="/edit-profile" element={<Edit_Profile />} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  path="/home"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ padding: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h1>📖 AUDIOOKS</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {stories.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>Loading stories...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            stories.map((story) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={story.id} style={{ marginBottom: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2>{story.title}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>{story.short_desc}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img src={story.image_url} width="200" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <audio controls src={story.audio_url}></audio>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* If path doesn’t match, redirect to Welcome */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Route path="*" element={<Navigate to="/" />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Router>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default App;