import { useState } from "react";
import { auth, googleProvider } from "./firebase";
import {
  createUserWithEmailAndPassword,
    signInWithEmailAndPassword,
      sendEmailVerification,
        signInWithPopup,
        } from "firebase/auth";
        import { useNavigate } from "react-router-dom"; // ✅ Import navigate
        import "./Login.css"; // import the CSS file

        export default function Login({ onLogin }) {
          const [email, setEmail] = useState("");
            const [password, setPassword] = useState("");
              const [error, setError] = useState("");
                const [success, setSuccess] = useState("");
                  const [acceptTerms, setAcceptTerms] = useState(false);

                    const navigate = useNavigate(); // ✅ Hook for redirect

                      // 🔹 Sign Up
                        const handleSignUp = async () => {
                            if (!email || !password) {
                                  setError("Please enter email and password.");
                                        return;
                                            }
                                                if (!acceptTerms) {
                                                      setError("You must accept Terms & Conditions before signing up.");
                                                            return;
                                                                }
                                                                    try {
                                                                          const userCredential = await createUserWithEmailAndPassword(
                                                                                  auth,
                                                                                          email,
                                                                                                  password
                                                                                                        );
                                                                                                              await sendEmailVerification(userCredential.user);
                                                                                                                    setSuccess("Signup successful! Please check your email to verify.");
                                                                                                                          setError("");
                                                                                                                                onLogin(userCredential.user);

                                                                                                                                      // ✅ Redirect to Welcome screen
                                                                                                                                            navigate("/");
                                                                                                                                                } catch (err) {
                                                                                                                                                      setError(err.message);
                                                                                                                                                            setSuccess("");
                                                                                                                                                                }
                                                                                                                                                                  };

                                                                                                                                                                    // 🔹 Login
                                                                                                                                                                      const handleLogin = async () => {
                                                                                                                                                                          if (!email || !password) {
                                                                                                                                                                                setError("Please enter email and password.");
                                                                                                                                                                                      return;
                                                                                                                                                                                          }
                                                                                                                                                                                              try {
                                                                                                                                                                                                    const userCredential = await signInWithEmailAndPassword(
                                                                                                                                                                                                            auth,
                                                                                                                                                                                                                    email,
                                                                                                                                                                                                                            password
                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                        setSuccess("Login successful! Redirecting...");
                                                                                                                                                                                                                                              setError("");
                                                                                                                                                                                                                                                    onLogin(userCredential.user);

                                                                                                                                                                                                                                                          // ✅ Redirect to Welcome screen
                                                                                                                                                                                                                                                                navigate("/");
                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                          setError(err.message);
                                                                                                                                                                                                                                                                                setSuccess("");
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                        // 🔹 Google Login
                                                                                                                                                                                                                                                                                          const handleGoogleLogin = async () => {
                                                                                                                                                                                                                                                                                              if (!acceptTerms) {
                                                                                                                                                                                                                                                                                                    setError("You must accept Terms & Conditions before continuing.");
                                                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                        const result = await signInWithPopup(auth, googleProvider);
                                                                                                                                                                                                                                                                                                                              setSuccess("Login successful! Redirecting...");
                                                                                                                                                                                                                                                                                                                                    setError("");
                                                                                                                                                                                                                                                                                                                                          onLogin(result.user);

                                                                                                                                                                                                                                                                                                                                                // ✅ Redirect to Welcome screen
                                                                                                                                                                                                                                                                                                                                                      navigate("/");
                                                                                                                                                                                                                                                                                                                                                          } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                setError(err.message);
                                                                                                                                                                                                                                                                                                                                                                      setSuccess("");
                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                  <div className="login-page">
                                                                                                                                                                                                                                                                                                                                                                                        <div className="login-container">
                                                                                                                                                                                                                                                                                                                                                                                                {/* Logo */}
                                                                                                                                                                                                                                                                                                                                                                                                        <img
                                                                                                                                                                                                                                                                                                                                                                                                                  src="https://archive.org/download/img-20250811-wa-0028/IMG-20250811-WA0028.jpg"
                                                                                                                                                                                                                                                                                                                                                                                                                            alt="Audiooks Logo"
                                                                                                                                                                                                                                                                                                                                                                                                                                      className="login-logo"
                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2>Welcome to Audiooks</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="subtitle">Stories You Can Hear,Anywhere</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Email input */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Email address"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="input-field"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Password input */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="input-field"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Terms & Conditions */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="terms">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="checkbox"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    checked={acceptTerms}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={() => setAcceptTerms(!acceptTerms)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                I agree to the{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          href="https://sites.google.com/view/audiooks/home?authuser=3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      rel="noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Terms & Conditions and Privacy Policy
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Error / Success */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {error && <p className="error">{error}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {success && <p className="success">{success}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Buttons */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="button-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={handleLogin} className="btn login-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Login
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={handleSignUp} className="btn signup-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Sign Up
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="or">or</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Google Login */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={handleGoogleLogin} className="btn google-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            src="https://archive.org/download/google-g-logo_202508/Google__G__logo.png"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alt="Google"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Continue with Google
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }