import { useNavigate } from "react-router-dom";
import "./Subscription.css";
import { FaGift,FaCircleRight } from "react-icons/fa6";

export default function Subscription() {
  const navigate = useNavigate();

    return (
        <div
              style={{
                      width: "100vw",
                              minHeight: "100vh",
                                      display: "flex",
                                              flexDirection: "column",
                                                      backgroundColor: "#000",
                                                              color: "#fff",
                                                                      overflowY: "auto",
                                                                            }}
                                                                                >
                                                                                      {/* Top small image */}
                                                                                            <img
                                                                                                    src="https://archive.org/download/listening-headphones-storytelling-cozy-listening-audio-story-person-headphones/listening%20headphones%20storytelling%2C%20cozy%20listening%2C%20audio%20story%20person%20headphones.jpg"
                                                                                                            alt="Listening"
                                                                                                                    style={{
                                                                                                                              width: "100%",
                                                                                                                                        height: "25vh",
                                                                                                                                                  objectFit: "cover",
                                                                                                                                                          }}
                                                                                                                                                                />

                                                                                                                                                                      {/* Background section with text + buttons */}
                                                                                                                                                                            <div className="background-section">
                                                                                                                                                                                    <div className="subscription-box">
                                                                                                                                                                                              {/* Heading */}
                                                                                                                                                                                                        <h2>
                                                                                                                                                                                                                    Access all contents <br /> Upgrade to Premium Now
                                                                                                                                                                                                                              </h2>

                                                                                                                                                                                                                                        {/* Premium Button */}
                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                              className="premium-button"
                                                                                                                                                                                                                                                                          onClick={() =>
                                                                                                                                                                                                                                                                                        window.open("https://rzp.io/rzp/premium-99", "_blank")
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                         ₹99 / month — No Ads — Full Access
                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                              {/* OR separator */}
                                                                                                                                                                                                                                                                                                                                                        <h3 className="or-text">OR</h3>

                                                                                                                                                                                                                                                                                                                                                                  {/* Free Content Text (not a button) */}
                                                                                                                                                                                                                                                                                                                                                                            <p className="free-text">Access free content with Ads</p>

                                                                                                                                                                                                                                                                                                                                                                                      {/* Let's Get Started Button */}
                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                            className="start-button"
                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => navigate("/preferences")}
                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                             Let&apos;s Get Started  
                                                                                                                                                                                                                                                                                                                                                                                                                                             <FaCircleRight style={{ marginLeft: "8px", verticalAlign: "middle" }}/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* 🎁 Support Us button (sticky footer-style) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="support-button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.open("https://rzp.io/rzp/Audiooks-donation", "_blank")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Support Us
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <FaGift style={{ marginLeft: "8px"}}/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }