import { useNavigate } from "react-router-dom";

export default function Welcome() {
  const navigate = useNavigate();

    return (
        <div
              style={{
                      width: "100vw",
                              minHeight: "100vh",
                                      display: "flex",
                                              flexDirection: "column",
                                                      backgroundColor: "#000",
                                                            }}
                                                                >
                                                                      {/* Smaller Welcome GIF */}
                                                                            <img
                                                                                    src="https://archive.org/download/welcome-audiooks/Welcome_audiooks.gif"
                                                                                            alt="Welcome"
                                                                                                    style={{
                                                                                                              width: "100%",
                                                                                                                        height: "20vh", // 👈 reduced height
                                                                                                                                  objectFit: "cover",
                                                                                                                                            marginBottom: "10px",
                                                                                                                                                    }}
                                                                                                                                                          />

                                                                                                                                                                {/* Main Full Image */}
                                                                                                                                                                      <img
                                                                                                                                                                              src="https://archive.org/download/audiooksrededited_copy_1080x2160/audiooksrededited_copy_1080x2160.png"
                                                                                                                                                                                      alt="Audiooks Background"
                                                                                                                                                                                              style={{
                                                                                                                                                                                                        width: "100%",
                                                                                                                                                                                                                  height: "auto",
                                                                                                                                                                                                                            objectFit: "cover",
                                                                                                                                                                                                                                      flexGrow: 1,
                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                          {/* Next Button (responsive with relative units) */}
                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                  width: "100%",
                                                                                                                                                                                                                                                                                            padding: "20px",
                                                                                                                                                                                                                                                                                                      display: "flex",
                                                                                                                                                                                                                                                                                                                justifyContent: "center",
                                                                                                                                                                                                                                                                                                                          backgroundColor: "#000",
                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                          onClick={() => navigate("/subscription")}
                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                padding: "clamp(12px, 2vh, 20px) clamp(40px, 6vw, 80px)", // responsive padding
                                                                                                                                                                                                                                                                                                                                                                                            fontSize: "clamp(16px, 2.5vw, 22px)", // responsive font size
                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                    color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                background: "linear-gradient(135deg, #FF512F, #F09819)",
                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "50px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                boxShadow: "0 6px 18px rgba(0,0,0,0.4)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: "min(80%, 700px)", // scales up but max 320px wide
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Next
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }